name: Terraform CI/CD - Destroy (Azure)

on:
  workflow_dispatch:   # Apenas execução manual

permissions:
  contents: read
  id-token: write

env:
  TF_WORKING_DIR: .
  TF_VERSION: "1.6.0"

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          export ARM_USE_OIDC=true
          export ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}
          terraform init -input=false -no-color

      - name: Terraform Destroy
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform destroy -auto-approve
